apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque # Opaque is the most common type of secret, it is used to store arbitrary data. Other types are: kubernetes.io/service-account-token, kubernetes.io/dockercfg, kubernetes.io/dockerconfigjson, kubernetes.io/basic-auth, kubernetes.io/ssh-auth, kubernetes.io/tls
data:
  DB_PASSWORD: bXlTZWN1cmVQYXNz # "mySecurePass" en base64 , echo -n "mySecurePass" | base64
