apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-app
  ports:
    - port: 80
      targetPort: 8080   # en este caso no lo usamos, pero ejemplificamos
      nodePort: 30081
  type: NodePort
