apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-app
  template:
    metadata:
      labels:
        app: pv-app
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            echo "Starting to write logs every 5s..." ;
            i=0;
            while true; do
              echo "Log line $i" >> /data/log.txt;
              i=$((i+1));
              sleep 5;
            done
        volumeMounts:
        - name: my-volume
          mountPath: /data
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-pvc
